# Generated by Django 4.2.5 on 2023-09-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('pic', models.ImageField(upload_to='user_img/')),
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
